:doctitle: Descriptive and Informative Summaries

== Brief

This assignment was to write both a descriptive summary (50 words), and informative summary (200 words), of the following article:

The Auto Industry Is Going Green. Will Workers Go Along for the Ride? +
BY JUSTIN WORLAND +
AUGUST 12, 2021

== Deliverables
=== Summaries: Descriptive and Informative

|===
a|=== The Original Article +
xref:attachment$auto_green.pdf[The Auto Industry Is Going Green. Will Workers Go Along for the Ride?] +
[3609 words]

a|=== The Descriptive Summary +

This article reports on the transition from traditional to green in the automotive industry in Ohio. It discusses the political, social, and investment agendas of stakeholders and the regional and global competition and risks. It describes the multi-layered uncertainties limiting the region’s vision of its future identity and security.

[49 words]

a|=== The Informative Summary +

The automotive industry in Ohio is attempting to reinvent itself by transitioning to the production of electric vehicles. Many traditional plants closed production in the last ten years with significant job losses and erosion of the region’s industrial identity.

While there is political will at both federal and state level, there remains no clear vision of how the industry or region might look post transition. Stakeholders face fierce competition both locally and globally.

Some companies have already invested in converting their production facilities, and in new allied industries e.g., battery production. Support industries will also change, and different skills will be required in e-vehicle production for which the reskilling of workers has already begun.

E-vehicle production requires fewer workers than traditional, and studies mentioned indicate that green jobs do not always go to the same workers in their original locations globally. Unions see this as an opportunity to create better jobs while some new companies see it as a way of avoiding unionisation. Workers in Ohio will therefore not be guaranteed secure, well-paid jobs.

The status remains volatile and uncertain, waiting for concrete, bipartisan political choices, commitment, funding, and how competition plays out at a local and global level. The transition will not be easy.

[205 words]

|===

== Reflection
=== Why I chose the Summaries assignment

I chose this assignment as it was one of the very first assignments in the course and was a type of task that was quite different to the kind of work I was used to. I was surprised to have enjoyed, thoroughly, parring down the content into its essence. Before the module, I was unaware that these kinds of summaries existed.

At first I wasn't sure how well I would be able to do this task but I was satisfied with my work, and this was reflected in the positive feedback I received. It was an early confirmation that choosing to do the course was a good decision, and that the career direction I was changing to was right for me. I realised how much I enjoy writing and that I probably should have done the switch sooner.

=== Which skills were demonstrated

The skills demonstrated were

* Understanding the purposes of the two different types of summary and applying the respective styles effectively.

* Condensing the information into much fewer words while retaining the message of the original article.

=== What I learnt from writing the summaries

* I learnt about these types of summary, their purposes, who the respective audiences might be, and their style rules.
* I also learnt about the process of extracting the relevant facts from the original article and reassembling them into the two condensed formats.
* I learnt that getting to the final format was an iterative process.

The TW5211 lecture we had before starting this assignment dealt with writing style and I tried to apply these principles into the task:

* Word choice
* Sentence construction
* Sentence length
* Transitions
* Tone

I found all of the above categories important in the task.
I tried to remember the instruction:  "Professional writing style must be readable: clear, concise, fluent, and precise" (TW5211 Week 3 presentation).

It was a fine balance between the completeness of the information and word count. The purposes of the two summaries are different, but must assist the reader in making the decision on whether to read the full article or not.

=== References

Liz Gabbett, L. (2022) 'Writing Style', _TW5211: Principles of Professional and Technical Communication and Information_, University of Limerick, unpublished.
