:doctitle: Podcast Assignment


== Brief
Develop a professional instructional podcast that achieves specific learning outcomes and meets the needs of a particular audience, while also adhering to principles of universal design for learning (UDL) . Write a script and record and edit audio files using industry-standard software.


== Topic Chosen


=== How to Choose the Perfect Tree for your Space, a Guide for Home Owners and Managers of Community Outdoor Spaces

== Deliverables


|===
|Script |The Podcast Recording

|xref:attachment$Nicole_Paterson-Jones_EL6041_Final.pdf[How to Choose the Perfect Tree for your Space]
|xref:attachment$Nicole_Paterson-Jones_EL6041_Final.mp3[How to Choose the Perfect Tree for your Space]
|===

== Reflection

=== Why I chose the Podcast assignment
This assignment was one that I found difficult initially. The reasons for this were

* I am not a natural teacher or someone who likes speaking in public.
* I did not have a quiet place to record in.
* I did not have any recording equipment and could not afford to buy or rent any.

I chose this podcast because it forced me to  get out of my comfort zone. I had to come up with a strategy for getting the assignment done while dealing with the logistical difficulties and overcoming my discomfort.

=== Which skills were demonstrated
The skills demonstrated were:

* Researching: the subject matter, and suitable (free) tools for recording
* Script writing
* Developing learning outcomes
* Recording and editing audio using Audacity
* Speaking clearly and confidently

=== What I Learnt from developing the podcast

==== How to approach the task

I developed a way of approaching a task like this by starting with the things I could do or prepare before I starting the part I was the least confident about i.e., the recording, which made the process less intimidating. Once these tasks were out of the way, what was left seemed less daunting.

==== Time management

I learnt that it is hard to judge how long recording and editing will take and so starting as early as possible is essential.

==== Applying the theory

I learnt about Blooms Taxonomy for measurable verbs and applied this in the learning outcomes, and Gagne's Nine Events of Instruction, as best fitting a podcast e.g., one can elicit performance but not always give feedback on it:

* Gain Attention (musical intro)
* Inform learners of Learning outcomes
* Relate this lesson to previous lessons
* Present new content
* Provide learning guidance
* Elicit performance
* Provide feedback (limited possibility due to asynchronous consumption, and nature of podcast)
* Assess performance
* Enhance retention and transfer


==== Recording and editing audio

I learnt how to use Audacity to edit the audio recordings.

==== Applying design principles

I applied the three principles of UDL (CAST, 2020): in project as far as possible given the medium:

* *Recruiting Interest:* The podcast supported individual choice, autonomy and value.

* *Perception:* visual and audio versions of the podcast were available.
* *Physical action and Expression and Communication:* actions were guided by both versions of the podcast. Other tools were flexible and fully the choice of the consumer.
* *Self Regulation:* consumers were encouraged to analyse their particular scenario and reflect on their solution.
* *Comprehension:* comprehensive background knowledge was supplied.
* *Executive functions:* appropriate goal setting was encouraged, and planning and strategy development was supported.
* *Sustaining Effort and Persistence:* the podcast was designed to be engaging and interesting.

=== References

Anderson, L.W., and Krathwohl, D.R., (Editors), and others, (2001) _A Taxonomy for Learning, Teaching, and Assessing: A Revision of Bloom’s Taxonomy of Educational Objectives_. Addison Wesley, Massachusetts, USA.

Gagné, R.M., Briggs, Leslie.J., and Wager, Walter.W. (1992) Principles Of Instructional Design, 4th ed. Harcourt Brace College Publishers, California, USA

Universal Design for Learning Guidelines (2024), available: https://udlguidelines.cast.org/ Universal Design for Learning Guidelines [accessed 12 April 2024].



